train_dataset: mini-imagenet
train_dataset_args: {split: train}
tval_dataset: mini-imagenet
tval_dataset_args: {split: test}
val_dataset: mini-imagenet
val_dataset_args: {split: val}

model: meta-baseline
model_args: 
    encoder: resnet12
    encoder_args: {}

n_way: 5
n_shot: 1
n_query: 10
train_batches: 200
ep_per_batch: 1
save_epoch: 100

max_epoch: 1000
optimizer: sgd
optimizer_args: {lr: 0.001, weight_decay: 5.e-4}


visualize_datasets: True
